### ISSUE TITLE
Integration with Boostnote

### ISSUE THREAD

**Issue by azarezade** [sobhe/moratab#31]
Is it possible to integrate Moratab with [Boostnote](https://github.com/BoostIO/Boostnote/), which is a great note taking app based on Markdown?
That would be great to use Boostnote with Persian support!

**Comment by nournia** [comment]
It seems that Boostnote uses CodeMirror for editing Markdown and we need to completey rewrite Moratab to be compatible with CodeMirror.
It would be great if you could do that :)

**Comment by azarezade** [comment]
So I close the issue, since it needs major modification...
